frr version 10.4.1
frr defaults traditional
hostname leaf1
log syslog informational
log facility local4
agentx
zebra nexthop-group keep 1
fpm address 127.0.0.1
no fpm use-next-hop-groups
service integrated-vtysh-config
!
ip prefix-list PL_LoopbackV4 seq 5 permit 1.1.1.1/32
!
route-map RM_SET_SRC permit 10
 set src 1.1.1.1
exit
!
password zebra
enable password zebra
!
vrf Vrf_Type5
 ip router-id 1.1.1.1
 vni 10999
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
router bgp 65001
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 neighbor 11.11.11.11 remote-as 65000
 neighbor 11.11.11.11 ebgp-multihop 5
 neighbor 22.22.22.22 remote-as 65000
 neighbor 22.22.22.22 ebgp-multihop 5
 neighbor 192.168.10.3 remote-as 65000
 neighbor 192.168.12.3 remote-as 65000
 !
 address-family ipv4 unicast
  network 10.1.1.1/32
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 11.11.11.11 activate
  neighbor 22.22.22.22 activate
  advertise-all-vni
  vni 100
   route-target import 65500:100
   route-target export 65500:100
  exit-vni
 exit-address-family
exit
!
router bgp 65001 vrf Vrf_Type5
 no bgp ebgp-requires-policy
 !
 address-family ipv4 unicast
  network 10.80.1.0/24
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 1.1.1.1:10999
  route-target import 64999:10999
  route-target export 64999:10999
 exit-address-family
exit
!
access-list all seq 5 permit any
!
ip protocol bgp route-map RM_SET_SRC
!
ip nht resolve-via-default
!
ipv6 nht resolve-via-default
!
